{{- if .Values.global.enabledComponents.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.appName }}-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secret }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
{{- end }}
