{{- if .Values.global.enabledComponents.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.appName }}-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  DB_HOST: "{{ .Values.secret.DB_HOST }}"
  DB_NAME: "{{ .Values.secret.DB_NAME }}"
  DB_USER: "{{ .Values.secret.DB_USER }}"
  DB_PASS: "{{ .Values.secret.DB_PASS }}"
{{- end }}
